name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      # Publish the site
      - name: Publish
        run: dotnet publish BlazorApp1.sln -c:Release -o:public -p:GHPages=true

      # Fixes for gh-pages
      - name: Change base-tag in index.html from / to BlazorApp1
        run: sed -i 's/<base href="\/" \/>/<base href="\/webassembly\/" \/>/g' public/wwwroot/index.html
  
      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/wwwroot
          force_orphan: true
